language: php

php:
  - 7.2.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database boilerplate_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --verbose